package com.zhiyou.model;
// Generated 2017-11-22 16:10:07 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Blogviews generated by hbm2java
 */
public class Blogviews implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int blogId;
	private Date insertTime;
	private String ip;
	private Integer userId;

	public Blogviews() {
	}

	public Blogviews(int blogId) {
		this.blogId = blogId;
	}

	public Blogviews(int blogId, Date insertTime, String ip, Integer userId) {
		this.blogId = blogId;
		this.insertTime = insertTime;
		this.ip = ip;
		this.userId = userId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getBlogId() {
		return this.blogId;
	}

	public void setBlogId(int blogId) {
		this.blogId = blogId;
	}

	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
