package com.zhiyou.model;
// Generated 2017-11-22 16:10:07 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String email;
	private String pwd;
	private String oldPwd;
	private String newPwd;
	private String regPwd;
	private String userName;
	private String nickName;
	private String avatar;
	private Integer age;
	private String introduction;
	private Date registTime;
	private Date updateTime;
	private Set blogtypes = new HashSet(0);
	private Set blogs = new HashSet(0);

	public User() {
	}

	public User(String email, String pwd, String userName, String nickName, String avatar, Integer age,
			String introduction, Date registTime, Date updateTime, Set blogtypes, Set blogs) {
		this.email = email;
		this.pwd = pwd;
		this.userName = userName;
		this.nickName = nickName;
		this.avatar = avatar;
		this.age = age;
		this.introduction = introduction;
		this.registTime = registTime;
		this.updateTime = updateTime;
		this.blogtypes = blogtypes;
		this.blogs = blogs;
	}

	
	public User(String userName, Integer age) {
		super();
		this.userName = userName;
		this.age = age;
	}

	
	public String getRegPwd() {
		return regPwd;
	}

	public void setRegPwd(String regPwd) {
		this.regPwd = regPwd;
	}

	public String getOldPwd() {
		return oldPwd;
	}

	public void setOldPwd(String oldPwd) {
		this.oldPwd = oldPwd;
	}

	public String getNewPwd() {
		return newPwd;
	}

	public void setNewPwd(String newPwd) {
		this.newPwd = newPwd;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public Date getRegistTime() {
		return this.registTime;
	}

	public void setRegistTime(Date registTime) {
		this.registTime = registTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set getBlogtypes() {
		return this.blogtypes;
	}

	public void setBlogtypes(Set blogtypes) {
		this.blogtypes = blogtypes;
	}

	public Set getBlogs() {
		return this.blogs;
	}

	public void setBlogs(Set blogs) {
		this.blogs = blogs;
	}




	
}
