package com.zhiyou.model;
// Generated 2017-11-22 16:10:07 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Blog generated by hbm2java
 */
public class Blog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Blogtype blogtype;
	private User user;
	private String title;
	private String content;
	private Date insertTime;
	private String insertUser;
	private Date updateTime;
	private Integer views;

	private Integer blogTypeId;
	private Integer userId;
	public Blog() {
	}

	public Blog(User user) {
		this.user = user;
	}

	public Blog(Blogtype blogtype, User user, String title, String content, Date insertTime, String insertUser,
			Date updateTime, Integer views) {
		this.blogtype = blogtype;
		this.user = user;
		this.title = title;
		this.content = content;
		this.insertTime = insertTime;
		this.insertUser = insertUser;
		this.updateTime = updateTime;
		this.views = views;
	}

	public Integer getBlogTypeId() {
		return blogTypeId;
	}

	public void setBlogTypeId(Integer blogTypeId) {
		this.blogTypeId = blogTypeId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Blogtype getBlogtype() {
		return this.blogtype;
	}

	public void setBlogtype(Blogtype blogtype) {
		this.blogtype = blogtype;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	public String getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(String insertUser) {
		this.insertUser = insertUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getViews() {
		return this.views;
	}

	public void setViews(Integer views) {
		this.views = views;
	}

	

}
